apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: httpd
          ports:
            containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      